feat(producerjson): add original producerjson smart contract
eoscostarica/eoscr-smart-contracts pull request #6
Opened 2022-03-06 15:20 UTC by xavier506

2022-03-07 07:32 UTC, leisterfrancisco requested changes

2022-03-07 07:32 UTC, leisterfrancisco commented on producerjson/README.md
> +cleos get table producerjson producerjson producerjson
cleos `-u <endpoint>` get table producerjson producerjson producerjson

2022-03-07 07:32 UTC, leisterfrancisco commented on producerjson/README.md
> +cleos push action producerjson set '{"owner":"your_account", "json": "your_json"}' -p your_account@active
cleos `-u <endpoint>` ...

2022-03-07 07:32 UTC, leisterfrancisco commented on producerjson/README.md
> +cleos push action producerjson set '{"owner":"teamgreymass", "json": "'`printf %q $(cat bp.json | tr -d "\r")`'"}' -p teamgreymass@active
cleos `-u <endpoint>` ...

2022-03-07 07:32 UTC, leisterfrancisco commented on producerjson/README.md
> +cleos push action producerjson del '{"owner":"your_account"}' -p your_account@active
cleos `-u <endpoint>` ...

2022-03-07 07:32 UTC, leisterfrancisco commented on producerjson/README.md
> +eosiocpp -g producerjson.abi producerjson.cpp && eosiocpp -o producerjson.wast producerjson.cpp
What compile are we using here?

https://developers.eos.io/welcome/latest/getting-started-guide/hello-world/#procedure-to-compile-and-deploy

2022-03-07 07:32 UTC, leisterfrancisco commented on producerjson/README.md
> +cleos set contract producerjson producerjson -p producerjson@active
cleos `-u <endpoint>` ...

2022-03-08 13:31 UTC, xavier506 reviewed
LGTM

2022-03-08 13:32 UTC, merged